Added a test for the version
The CMakelists.txt and debian/changelog need to remain synchronized so I added
a test which should help me fix the version when necessary.

Bumped the version to 2.3 since the fix to the CRC32 computation is a pretty
major fix.

diff --git a/dev/version b/dev/version
--- a/dev/version
+++ b/dev/version
@@ -25,9 +25,23 @@
 MAJOR=`grep 'set( ZIPIOS_VERSION_MAJOR ' CMakeLists.txt | sed -e 's/.*ZIPIOS_VERSION_MAJOR //' -e 's/ .*//'`
 MINOR=`grep 'set( ZIPIOS_VERSION_MINOR ' CMakeLists.txt | sed -e 's/.*ZIPIOS_VERSION_MINOR //' -e 's/ .*//'`
 PATCH=`grep 'set( ZIPIOS_VERSION_PATCH ' CMakeLists.txt | sed -e 's/.*ZIPIOS_VERSION_PATCH //' -e 's/ .*//'`
+BUILD=`grep 'set( ZIPIOS_VERSION_BUILD ' CMakeLists.txt | sed -e 's/.*ZIPIOS_VERSION_BUILD //' -e 's/ .*//'`
 
 VERSION=${MAJOR}.${MINOR}
 FULL_VERSION=${MAJOR}.${MINOR}.${PATCH}
+COMPLETE_VERSION=${MAJOR}.${MINOR}.${PATCH}.${BUILD}
+
+# To verify, make sure the version in the changelog matches
+CHANGELOG_VERSION=`sed -n -e 1p debian/changelog | sed -e 's/.*(//' -e 's/\~.*//'`
 
 #echo $FULL_VERSION
+#echo $COMPLETE_VERSION
+#echo $CHANGELOG_VERSION
+
+if test "$COMPLETE_VERSION" != "$CHANGELOG_VERSION"
+then
+	echo "error: complete version from CMakeLists.txt is $COMPLETE_VERSION, version in changelog is $CHANGELOG_VERSION"
+	exit 1
+fi
+
 
